### ISSUE TITLE
BVP does not correspond to each frame

### ISSUE THREAD

**Issue by Dylan-H-Wang** [KegangWangCCNU/RLAP-dataset#1]
Hi,

Thank you for the awesome work on this rPPG dataset!

One issue I encountered when I tried to add RLAP to rPPG-toolbox, I found that the length of BVP signals does not equal to the number of frames. For example, in `p001/R2`, the number of video frames is 3630 while the length of bvp is 2444.

Is there any solution to solve this? I did find useful code in your `PhysBench` repo. Or, should I resample the bvp signals based on the length of video frames by [this](https://github.com/ubicomplab/rPPG-Toolbox/blob/ff597bf8eb55c9db961709ec8b32fb142663fd78/dataset/data_loader/BaseLoader.py#L583C14-L583C14)?

**Comment by KegangWangCCNU** [comment]
This is not an issue. Please read the description of the file structure carefully. All video frames and BVP signals have timestamps. You need to align the timestamps and then use an interpolation algorithm. For specific methods, please refer to Loader_CCNU in PhysBench. 

The purpose of this is to ensure strict synchronization, which is important for training. You can see a similar approach in the PURE dataset.

**Comment by KegangWangCCNU** [comment]
Hi, Dylan

Do you have any more questions? Is the data loading correctly now? Would love to hear any feedback.

**Comment by Dylan-H-Wang** [comment]
Sorry for the delay. Yes, it helps to solve the issue, thank you!
For other's convenience, you may refer to this snippet for pre-processing RLAP:

https://github.com/KegangWangCCNU/PhysBench/blob/33df17457fd5dc04ad9505065e8b4953e275d119/utils.py#L236-L258
```python
class LoaderCCNU(Loader):


    def __call__(self, vid):
        vid = f'{self.base}{vid}'
        frames_ts = '/'.join(vid.split('/')[:-1])+'/frames_timestamp.csv'
        bvp = '/'.join(vid.split('/')[:-1])+'/BVP.csv'
        ts = pd.read_csv(frames_ts)['timestamp'].values
        x, y = pd.read_csv(bvp).loc[:, ['timestamp', 'bvp']].drop_duplicates(subset=['timestamp']).values.T
        f_i = UnivariateSpline(x, y, s=0)
        bvp = f_i(pd.read_csv(frames_ts)['timestamp'].values)
        def _1():
            cap = cv2.VideoCapture(vid)
            while 1:
                _, frame = cap.read()
                if _:
                    yield cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                else:
                    break
            cap.release()
        class _2:
            def __iter__(self):
                return _1()
        return _2(), bvp, ts
```
